Homework Spring Boot intro.
UniyatYura/bookstore pull request #1
Opened 2023-09-20 10:48 UTC by UniyatYura

2023-09-20 11:39 UTC, okuzan requested changes

2023-09-20 11:39 UTC, okuzan commented on src/main/java/mate/academy/bookstore/repository/BookRepository.java
> +public interface BookRepository {
you can extend JpaRepository instead of writing the methods out manually

2023-09-20 11:39 UTC, okuzan commented on src/main/java/mate/academy/bookstore/repository/impl/BookRepositoryImpl.java
> +            throw new RuntimeException("Can't get all books ", e);
better throw your own data processing exception instead of a generic one

2023-09-22 10:56 UTC, kozhukhovsky approved these changes

2023-09-22 18:12 UTC, merged